/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package methodreference;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 *
 * @author Orenda
 */
class Product {

    int id;
    String name;
    float price;

    public Product(int id, String name, float price) {
        this.id = id;
        this.name = name;
        this.price = price;
    }
}

public class LamdaFrame extends javax.swing.JFrame {

    /**
     * Creates new form LamdaFrame
     */
    public LamdaFrame() {
        initComponents();
        lamdaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                char[] characters = {'1', '2', '3', '4', ' ', 'k', 'g'};
                System.out.println(new String(characters));

                List<String> list = new ArrayList<String>();
                list.add("ankit");
                list.add("mayank");
                list.add("irfan");
                list.add("jai");
                List<Product> productsList = new ArrayList<Product>();
                //Adding Products  
                productsList.add(new Product(1, "HP Laptop", 25000f));
                productsList.add(new Product(2, "Dell Laptop", 30000f));
                productsList.add(new Product(3, "Lenevo Laptop", 28000f));
                productsList.add(new Product(4, "Sony Laptop", 28000f));
                productsList.add(new Product(5, "Apple Laptop", 90000f));

                Pattern patern = Pattern.compile("\\D*");
                var sorted = list.stream().filter(x -> patern.matcher(x).matches());

                Float totalPrice = productsList.stream()
                        .map(product -> product.price)
                        .reduce(0.0f, (sum, price) -> sum + price);   // accumulating price  
                System.out.println(totalPrice);

                List<Float> prices = new ArrayList<Float>();
                prices.add(10.3f);
                prices.add(16.3f);
                prices.add(10.7f);
                prices.add(5.3f);
                prices.add(6.9f);
                prices.add(1.2f);
                prices.add(10.3f);
                System.out.println("Printed With");
                prices.forEach(System.out::println);
                var reduceTotal = prices.stream().reduce(10.0f, (a, b) -> a + b);
                Optional<String> longestString = list.stream().reduce((w1, w2) -> w1.length() > w2.length() ? w1 : w2);
                System.out.println("Longest String....");

                longestString.ifPresent(System.out::println);

                longestString.ifPresent(x -> {
                    System.out.println(x);
                });
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lamdaButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lamdaButton.setText("Click This");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lamdaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lamdaButton)
                    .addComponent(jButton2))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LamdaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LamdaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LamdaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LamdaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LamdaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton lamdaButton;
    // End of variables declaration//GEN-END:variables
}
